default: &default
  condenser:
    url: <%= ENV.fetch("CONDENSER_URL", "http://localhost:3000") %>

  wringer:
    url: <%= ENV.fetch("WRINGER_URL", "http://localhost:3009") %>

development:
  <<: *default

staging:
  condenser:
    url: <%= ENV.fetch("CONDENSER_URL", "https://footlight-condenser-test-c24c162bb7c8.herokuapp.com") %>

production:
  <<: *default